version: '3.1'
services:
  redis:
    image: 'redis:7.0'
    networks:
      - hmpps
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

networks:
  hmpps:
