/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/video-link-booking': {
    /** Endpoint to support the creation of video link bookings */
    post: operations['create']
  }
  '/probation-teams/enabled': {
    /** Endpoint to return a list of enabled probation teams for video link bookings */
    get: operations['enabledProbationTeams']
  }
  '/courts/enabled': {
    /** Endpoint to return a list of enabled courts for video link bookings */
    get: operations['enabledCourts']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /**
     * @description
     *       The appointment or appointments associated with the prisoner.
     *
     *       There should only ever be one appointment for a probation meeting.
     *
     *       Court meetings can have up to 3 meetings, a pre, main hearing and post meeting. They must always have a main meeting.
     *
     *       Appointment dates and times must not overlap.
     */
    Appointment: {
      /**
       * @description The appointment type
       * @example VLB_COURT_MAIN
       * @enum {string}
       */
      type: 'VLB_PROBATION' | 'VLB_COURT_PRE' | 'VLB_COURT_MAIN' | 'VLB_COURT_POST'
      /**
       * @description The location key for the appointment
       * @example PVI-A-1-001
       */
      locationKey: string
      /**
       * Format: date
       * @description The future date for which the appointment will start
       * @example 2022-12-23
       */
      date: string
      /**
       * Format: partial-time
       * @description Start time for the appointment on the day
       * @example 10:45
       */
      startTime: string
      /**
       * Format: partial-time
       * @description End time for the appointment on the day
       * @example 11:45
       */
      endTime: string
    }
    /** @description The request with the new video link booking details */
    CreateVideoBookingRequest: {
      /**
       * @description The booking type
       * @example COURT
       * @enum {string}
       */
      bookingType: 'COURT' | 'PROBATION'
      /** @description The prisoner or prisoners associated with the video link booking */
      prisoners: components['schemas']['PrisonerDetails'][]
      /**
       * Format: int64
       * @description The court identifier is needed if booking type is COURT, otherwise null
       * @example 123456
       */
      courtId?: number
      /**
       * @description The court hearing type is needed if booking type is COURT, otherwise null
       * @example APPEAL
       * @enum {string}
       */
      courtHearingType?:
        | 'APPEAL'
        | 'APPLICATION'
        | 'BACKER'
        | 'BAIL'
        | 'CIVIL'
        | 'CSE'
        | 'CTA'
        | 'IMMIGRATION_DEPORTATION'
        | 'FAMILY'
        | 'TRIAL'
        | 'FCMH'
        | 'FTR'
        | 'GRH'
        | 'MDA'
        | 'MEF'
        | 'NEWTON'
        | 'PLE'
        | 'PTPH'
        | 'PTR'
        | 'POCA'
        | 'REMAND'
        | 'SECTION_28'
        | 'SEN'
        | 'TRIBUNAL'
        | 'OTHER'
      /**
       * Format: int64
       * @description The probation team identifier is needed if booking type is PROBATION, otherwise null
       * @example 123456
       */
      probationTeamId?: number
      /**
       * @description The probation meeting type is needed if booking type is PROBATION, otherwise null
       * @example PSR
       * @enum {string}
       */
      probationMeetingType?: 'PSR' | 'RR'
      /**
       * @description Free text comments for the video link booking
       * @example Waiting to hear on legal representation
       */
      comments?: string
      /**
       * @description The video link for the appointment. Must be a valid URL
       * @example https://video.here.com
       */
      videoLinkUrl?: string
    }
    /** @description The prisoner or prisoners associated with the video link booking */
    PrisonerDetails: {
      /**
       * @description The prison code for the prisoner
       * @example PVI
       */
      prisonCode: string
      /**
       * @description The prisoner number (NOMIS ID)
       * @example A1234AA
       */
      prisonerNumber: string
      /**
       * @description
       *       The appointment or appointments associated with the prisoner.
       *
       *       There should only ever be one appointment for a probation meeting.
       *
       *       Court meetings can have up to 3 meetings, a pre, main hearing and post meeting. They must always have a main meeting.
       *
       *       Appointment dates and times must not overlap.
       */
      appointments: components['schemas']['Appointment'][]
    }
    ErrorResponse: {
      /** Format: int32 */
      status: number
      /** Format: int32 */
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** @description Describes the details of a probation team */
    ProbationTeam: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this probation team.
       * @example 12345
       */
      probationTeamId: number
      /**
       * @description A short code for this probation team.
       * @example NORTHWEST-PCC
       */
      code: string
      /**
       * @description A fuller description for this probation team
       * @example North West Primary Care
       */
      description: string
      /**
       * @description A boolean value to show whether enabled for video link bookings.
       * @example true
       */
      enabled: boolean
      /**
       * @description Notes relating to this probation team for opening hours, postal address, main contact.
       * @example Free form notes
       */
      notes?: string
    }
    /** @description Describes the details of a court */
    Court: {
      /**
       * Format: int64
       * @description An internally-generated unique identifier for this court.
       * @example 12345
       */
      courtId: number
      /**
       * @description A short code for this court.
       * @example AVONCC
       */
      code: string
      /**
       * @description A fuller description for this court
       * @example Avon Crown Court
       */
      description: string
      /**
       * @description A boolean value to show whether enabled for video link bookings.
       * @example true
       */
      enabled: boolean
      /**
       * @description Notes relating to this court for opening hours, postal address, main contact.
       * @example Free form notes
       */
      notes?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Endpoint to support the creation of video link bookings */
  create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateVideoBookingRequest']
      }
    }
    responses: {
      /** @description The unique identifier of the created video booking */
      201: {
        content: {
          'application/json': number
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Endpoint to return a list of enabled probation teams for video link bookings */
  enabledProbationTeams: {
    responses: {
      /** @description Probation teams */
      200: {
        content: {
          'application/json': components['schemas']['ProbationTeam'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Endpoint to return a list of enabled courts for video link bookings */
  enabledCourts: {
    responses: {
      /** @description Courts */
      200: {
        content: {
          'application/json': components['schemas']['Court'][]
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
