import { components } from '.'

export type Court = components['schemas']['Court']
export type ProbationTeam = components['schemas']['ProbationTeam']
export type Location = components['schemas']['Location']
export type Prison = components['schemas']['Prison']
export type AvailabilityRequest = components['schemas']['AvailabilityRequest']
export type AvailabilityResponse = components['schemas']['AvailabilityResponse']
export type AvailableLocationsRequest = components['schemas']['AvailableLocationsRequest']
export type AvailableLocationsResponse = components['schemas']['AvailableLocationsResponse']
export type CreateVideoBookingRequest = components['schemas']['CreateVideoBookingRequest']
export type RequestVideoBookingRequest = components['schemas']['RequestVideoBookingRequest']
export type AmendVideoBookingRequest = components['schemas']['AmendVideoBookingRequest']
export type ReferenceCode = components['schemas']['ReferenceCode']
export type VideoLinkBooking = components['schemas']['VideoLinkBooking']
export type PrisonAppointment = components['schemas']['PrisonAppointment']
export type ScheduleItem = components['schemas']['ScheduleItem']
export type RoomAttributes = components['schemas']['RoomAttributes']
export type RoomSchedule = components['schemas']['RoomSchedule']
export type CreateDecoratedRoomRequest = components['schemas']['CreateDecoratedRoomRequest']
export type CreateRoomScheduleRequest = components['schemas']['CreateRoomScheduleRequest']
export type AmendDecoratedRoomRequest = components['schemas']['AmendDecoratedRoomRequest']
export type AmendRoomScheduleRequest = components['schemas']['AmendRoomScheduleRequest']
