generic-service:
  nameOverride: hmpps-book-a-video-link-ui
  productId: "DPS093" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  serviceAccountName: hmpps-book-a-video-link

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-book-a-video-link-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-book-a-video-link-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    AUDIT_SQS_REGION: "eu-west-2"
    AUDIT_SERVICE_NAME: "hmpps-book-a-video-link-ui"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-book-a-video-link-ui:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      FEEDBACK_URL: "FEEDBACK_URL?"
      REPORT_A_FAULT_URL: "REPORT_A_FAULT_URL?"
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"
    sqs-hmpps-audit-secret:
      AUDIT_SQS_QUEUE_URL: "sqs_queue_url"
      AUDIT_SQS_QUEUE_NAME: "sqs_queue_name"
    maintenance:
      MAINTENANCE_MODE: "maintenance_mode?"
      MAINTENANCE_START_DATETIME: "maintenance_start_datetime?"
      MAINTENANCE_END_DATETIME: "maintenance_end_datetime?"
    feature-toggles:
      FEATURE_ENHANCED_PROBATION_JOURNEY: "FEATURE_MASTER_VLPM_TYPES"
      FEATURE_ADMIN_LOCATION_DECORATION: "FEATURE_ADMIN_LOCATION_DECORATION"
      FEATURE_ALTERED_COURT_JOURNEY: "FEATURE_ALTERED_COURT_JOURNEY"
      FEATURE_GREY_RELEASE_PRISONS: "FEATURE_GREY_RELEASE_PRISONS"

  allowlist:
    groups:
      - prisons
      - moj_cloud_platform
      - digital_staff_and_mojo

generic-prometheus-alerts:
  targetApplication: hmpps-book-a-video-link-ui
