---
# Per environment values which override defaults in hmpps-book-a-video-link-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-book-a-video-link-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-book-a-video-link-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: dps_alerts_non_prod