---
# Per environment values which override defaults in hmpps-book-a-video-link-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-book-a-video-link-ui-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://hmpps-book-a-video-link-ui-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    ACTIVITIES_API_URL: "https://activities-api-preprod.prison.service.justice.gov.uk"
    LOCATIONS_INSIDE_PRISON_API_URL: "https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: dps_alerts_non_prod
