---
# Per environment values which override defaults in hmpps-book-a-video-link-ui/values.yaml

generic-service:
  ingress:
    host: book-a-video-link.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://book-a-video-link.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    USER_PREFERENCES_API_URL: "https://hmpps-user-preferences.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "true"
    BOOK_A_VIDEO_LINK_API_URL: "https://book-a-video-link-api.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search.prison.service.justice.gov.uk"

  allowlist:
    royal-courts-of-justice: 178.248.34.43/32
    groups:
      - prisons
      - probation
      - moj_cloud_platform
      - digital_staff_and_mojo
      - analytic-platform

generic-prometheus-alerts:
  alertSeverity: hmpps-book-a-video-link-prod
