---
# Per environment values which override defaults in hmpps-book-a-video-link-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: book-a-video-link-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://book-a-video-link-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    USER_PREFERENCES_API_URL: "https://hmpps-user-preferences-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    BOOK_A_VIDEO_LINK_API_URL: "https://book-a-video-link-api-preprod.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-preprod.prison.service.justice.gov.uk"


  allowlist:
    pen-tester-1: 80.195.27.199/32
    pen-tester-2: 109.151.94.16/32
    groups:
      - prisons
      - moj_cloud_platform
      - digital_staff_and_mojo

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: hmpps-book-a-video-link-preprod
