---
# Per environment values which override defaults in hmpps-book-a-video-link-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: book-a-video-link-dev.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://book-a-video-link-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    USER_PREFERENCES_API_URL: "https://hmpps-user-preferences-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "true"
    BOOK_A_VIDEO_LINK_API_URL: "https://book-a-video-link-api-dev.prison.service.justice.gov.uk"
    PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: hmpps-book-a-video-link-dev
